In [16]:
import numpy as np

a = np.array(40)
b = np.array([1,2,3,4,5])
c = np.array([[12,22,13,23],[33,21,11,22]])
d = np.array([[[16,55,23,43],[56,66,33,90],[76,4,33,15]]])

print("Array A\n",a)
print("--------------------------")
print("Array B\n",b)
print("--------------------------")
print("Array C\n",c)
print("--------------------------")
print("Array D\n",d)
print("--------------------------")
print("A array dimension",a.ndim)
print("B array dimension",b.ndim)
print("C array dimension",c.ndim)
print("D array dimension",d.ndim)

Array A
 40
--------------------------
Array B
 [1 2 3 4 5]
--------------------------
Array C
 [[12 22 13 23]
 [33 21 11 22]]
--------------------------
Array D
 [[[16 55 23 43]
  [56 66 33 90]
  [76  4 33 15]]]
--------------------------
A array dimension 0
B array dimension 1
C array dimension 2
D array dimension 3


In [22]:
b = np.array([1,2,3,4,5])
b1 = b[1:5]
b1[2]=200
print(b1)
print(b)

[  2   3 200   5]
[  1   2   3 200   5]


In [24]:
arr = np.array([1,2,3,4,5])
arr2 = arr.copy()
print("original array without change",arr)
arr[0] = 42
print("original array with change",arr)
print("Copy of Original Array",arr2)

original array without change [1 2 3 4 5]
original array with change [42  2  3  4  5]
Copy of Original Array [1 2 3 4 5]


In [25]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0]=43
print(arr)
print(x)

[43  2  3  4  5]
[43  2  3  4  5]


In [35]:
arr = np.ones([3,4])
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
arr = np.eye(4)
print(arr)  #print the elements Diagonally

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [36]:
arr = np.diag([3,4,1,2]) # print different elements diagonally
print(arr)

[[3 0 0 0]
 [0 4 0 0]
 [0 0 1 0]
 [0 0 0 2]]


In [2]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.diag(arr))

[1 5 9]


In [4]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [9]:
rand = np.random.randint(0,10,3)
print(rand)

[6 7 7]


In [11]:
rand = np.random.rand(2,3)
print(rand)

[[0.68457084 0.11335694 0.24865517]
 [0.82693815 0.28679429 0.00140525]]


In [14]:
arr = np.array([1,2,3,5,6,10])
print(arr)
print("--------------------------------------")
print("Array after reshape")
arr2 = arr.reshape(3,2)
print(arr2)

[ 1  2  3  5  6 10]
--------------------------------------
Array after reshape
[[ 1  2]
 [ 3  5]
 [ 6 10]]


In [16]:
arr = np.random.randint(0,100,12)
print(arr)
print(" ")
arr = arr.reshape(4,3)
print(arr)
print(" ")
print("Array value is",arr[0][1])
print("Array value is",arr[1][0])
print(arr.shape)
print(" ")
arr = arr.reshape(-1,4)
print(arr)
print(" ")
arr = arr.reshape(2,-1)
print(arr)

[23 13 77 10 82 95 55 22  3 22 78 35]
 
[[23 13 77]
 [10 82 95]
 [55 22  3]
 [22 78 35]]
 
Array value is 13
Array value is 10
(4, 3)
 
[[23 13 77 10]
 [82 95 55 22]
 [ 3 22 78 35]]
 
[[23 13 77 10 82 95]
 [55 22  3 22 78 35]]


In [21]:
np.random.seed(145)
arr = np.random.randint(0,100,12)
print(arr)

[37 86 87 18 90 69  8 53 33 32 40 26]


In [24]:
np.random.seed(111)
arr = np.random.randint(1,500,30).reshape(6,5)
print(arr)
print("")
print(arr[2:,2:])
print("")
print(arr[3:5,2:4])

[[341 365 469 213  87]
 [276 170 323 119 467]
 [297 456 442   8 269]
 [267 450 369 217 285]
 [271 419  22  55 201]
 [ 38 461 231 187 269]]

[[442   8 269]
 [369 217 285]
 [ 22  55 201]
 [231 187 269]]

[[369 217]
 [ 22  55]]


In [25]:
arr = np.array([1,20,3,24,2,5,6,11,3,334,212,4,4,44])
slicing =arr[4:9]
print("new slicing",slicing)
print('new array',arr)

new slicing [ 2  5  6 11  3]
new array [  1  20   3  24   2   5   6  11   3 334 212   4   4  44]


In [26]:
print(type(slicing))
print(type(arr))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [27]:
slicing[:]=0
print("old slicing",slicing)
print("old array",arr)

old slicing [0 0 0 0 0]
old array [  1  20   3  24   0   0   0   0   0 334 212   4   4  44]


In [31]:
arr = np.arange(1,15)
print(arr)
print("even number from range")
print(arr[arr % 2 == 0])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
even number from range
[ 2  4  6  8 10 12 14]


In [30]:
arr = np.arange(1,15)
print(arr)
print("odd number from range")
print(arr[arr % 2 != 0])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
odd number from range
[ 1  3  5  7  9 11 13]


In [32]:
arr = np.arange(1,8)
print(arr+2)
print(arr*2)
print(arr**2)

[3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14]
[ 1  4  9 16 25 36 49]


In [35]:
arr = np.arange(1,15)
print(arr)
print(arr[arr%2==0])
print(arr[arr%2!=0])
print(arr[arr>8])
arr[arr%2==0]=0
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14]
[ 1  3  5  7  9 11 13]
[ 9 10 11 12 13 14]
[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0]


In [36]:
arr = np.array([10,20,30,4,5,6,7,11,2])
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.sqrt(arr))
print(np.sin(arr))
print(np.cos(arr))

2
30
8
2
[3.16227766 4.47213595 5.47722558 2.         2.23606798 2.44948974
 2.64575131 3.31662479 1.41421356]
[-0.54402111  0.91294525 -0.98803162 -0.7568025  -0.95892427 -0.2794155
  0.6569866  -0.99999021  0.90929743]
[-0.83907153  0.40808206  0.15425145 -0.65364362  0.28366219  0.96017029
  0.75390225  0.0044257  -0.41614684]


In [48]:
np.random.seed(122)
mat = np.random.randint(1,21,9).reshape(3,3)
print(mat)
print("")
print("sum of the matrix:",np.sum(mat))
print("cumsum of the matrix")
print(np.cumsum(mat))
print("min. element of  matrix",np.min(mat))
print("max. element of  matrix",np.max(mat))
print("--------------------------------------------------------")
print(np.sum(mat,axis=1)) #sum of 1st row
print("")
print(np.min(mat,axis=1))
print("")
print(np.max(mat,axis=1))
print("")
print(np.cumsum(mat,axis=1))

[[16 11 13]
 [17 13 16]
 [ 3 16 11]]

sum of the matrix: 116
cumsum of the matrix
[ 16  27  40  57  70  86  89 105 116]
min. element of  matrix 3
max. element of  matrix 17
--------------------------------------------------------
[40 46 30]

[11 13  3]

[16 17 16]

[[16 27 40]
 [17 30 46]
 [ 3 19 30]]


In [53]:
np.random.seed(122)
mat = np.random.randint(1,21,10)
print(mat)
print("")
np.random.shuffle(mat)
print(mat)
print("")
print(np.unique(mat, return_index = True, return_counts =True))
print("")
print(np.unique(mat).size)

[16 11 13 17 13 16  3 16 11 10]

[13 16 16 11 16 10 11 13 17  3]

(array([ 3, 10, 11, 13, 16, 17]), array([9, 5, 3, 0, 1, 8], dtype=int64), array([1, 1, 2, 2, 3, 1], dtype=int64))

6
