In [16]:
import numpy as np

a = np.array(40)
b = np.array([1,2,3,4,5])
c = np.array([[12,22,13,23],[33,21,11,22]])
d = np.array([[[16,55,23,43],[56,66,33,90],[76,4,33,15]]])

print("Array A\n",a)
print("--------------------------")
print("Array B\n",b)
print("--------------------------")
print("Array C\n",c)
print("--------------------------")
print("Array D\n",d)
print("--------------------------")
print("A array dimension",a.ndim)
print("B array dimension",b.ndim)
print("C array dimension",c.ndim)
print("D array dimension",d.ndim)

Array A
 40
--------------------------
Array B
 [1 2 3 4 5]
--------------------------
Array C
 [[12 22 13 23]
 [33 21 11 22]]
--------------------------
Array D
 [[[16 55 23 43]
  [56 66 33 90]
  [76  4 33 15]]]
--------------------------
A array dimension 0
B array dimension 1
C array dimension 2
D array dimension 3


In [22]:
b = np.array([1,2,3,4,5])
b1 = b[1:5]
b1[2]=200
print(b1)
print(b)

[  2   3 200   5]
[  1   2   3 200   5]


In [24]:
arr = np.array([1,2,3,4,5])
arr2 = arr.copy()
print("original array without change",arr)
arr[0] = 42
print("original array with change",arr)
print("Copy of Original Array",arr2)

original array without change [1 2 3 4 5]
original array with change [42  2  3  4  5]
Copy of Original Array [1 2 3 4 5]


In [25]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0]=43
print(arr)
print(x)

[43  2  3  4  5]
[43  2  3  4  5]


In [35]:
arr = np.ones([3,4])
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
arr = np.eye(4)
print(arr)  #print the elements Diagonally

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [36]:
arr = np.diag([3,4,1,2]) # print different elements diagonally
print(arr)

[[3 0 0 0]
 [0 4 0 0]
 [0 0 1 0]
 [0 0 0 2]]
