In [2]:
# Convert the below list into numpy array then display the array

import numpy as np
my_list = [1,2,3,4,5]

numpy_array = np.array(my_list)
print("Numpy_Array\n",numpy_array)

Numpy_Array
 [1 2 3 4 5]


In [4]:
#convert the below list into a numpy array then display the first and last index and then multiply each element by 2 and display the result
import numpy as np
my_list = [1, 2, 3, 4, 5]
numpy_array = np.array(my_list)
print("first element is:",numpy_array[0])
print("last element is:",numpy_array[4])
print("")
print(numpy_array*2)

first element is: 1
last element is: 5

[ 2  4  6  8 10]


In [13]:
#write a numpy program to create an array 10 zeroes, 10 ones and 10 fives
zero_arr = np.zeros(10)
print("An array of 10 zeros")
print(zero_arr)
print("")
ones_arr = np.ones(10)
print("An array of 10 ones")
print(ones_arr)
print("")
fives_arr = np.ones(10)*5
print("An array of 10 fives")
print(fives_arr)

An array of 10 zeros
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

An array of 10 ones
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

An array of 10 fives
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [15]:
# write a numpy program to create a 3*3 martrix with values ranging from 2 to 10
import numpy as np
arr = np.random.randint(2,10,9)
print("array value range from 2 to 10 is:")
print(arr)
print(" ")
arr = arr.reshape(3,3)
print("3*3 matrix is:")
print(arr)
print(" ")

array value range from 2 to 10 is:
[9 7 6 9 6 4 4 5 8]
 
3*3 matrix is:
[[9 7 6]
 [9 6 4]
 [4 5 8]]
 
