In [1]:
import numpy as np

In [6]:
arr = np.array([3,67,1,2,99,12,45,10])
sorted_array = np.sort(arr)
print("Existing array is ", arr)
print("======================================================")
print("sorted array in ascending", sorted_array)
print("======================================================")
new_sorted = np.sort(arr)[::-1]
print("sorted array in descending ", new_sorted)

Existing array is  [ 3 67  1  2 99 12 45 10]
sorted array in ascending [ 1  2  3 10 12 45 67 99]
sorted array in descending  [99 67 45 12 10  3  2  1]


In [7]:
# sort matrix along row

matrix = np.array([[3,1,2],[8,5,4]])
sorted_matrix = np.sort(matrix, axis=1)
print("Sorted Matrix (ascending along rows)")
print(sorted_matrix)

Sorted Matrix (ascending along rows)
[[1 2 3]
 [4 5 8]]


In [11]:
#NUMPY JOIN using vstack(), hstack(), concatenate()

#concatenate matrix using row wise
arr1 = np.array([[12,13],[2,3]])
arr2 = np.array([[3,3],[5,5]])
result = np.concatenate((arr1, arr2),axis=1)
print(result)

[[12 13  3  3]
 [ 2  3  5  5]]


In [16]:
#joining  matrix using vstack()

arr1 = np.array([12,13])
arr2 = np.array([5,5])
result = np.vstack((arr1, arr2)) #vertical join
print(result)

[[12 13]
 [ 5  5]]


In [15]:
#joining  matrix using hstack()

arr1 = np.array([12,13])
arr2 = np.array([5,5])
result = np.hstack((arr1, arr2)) #horizontal join
print(result)

[12 13  5  5]


In [20]:
arr = np.array([1,2,3,4,5,6])
mask = (arr > 2) & (arr < 6)
filtered_array = arr[mask]
# Print the filtered array
print("Filtered Array:", filtered_array)

Filtered Array: [3 4 5]


In [24]:
# variance and standard deviation

# Score of Class A students
classA= np.array([85, 88, 90, 92, 95])
# Score of Class A students
classB= np.array([70, 80, 85, 95, 100])
classA_mean=np.mean(classA)
classB_mean=np.mean(classB)
print("")
print("--------------------Mean----------------------")
print('Class A Score Average',classA_mean )
print('Class B Score Average',classB_mean )
print("----------------------------------------------")
classA_var=np.var(classA)
classB_var=np.var(classB)
print("")
print("----------------Variance-----------------------")
print('Class A variance',classA_var )
print('Class B variance',classB_var )
print("------------------------------------------------")
classA_std = np.std(classA)
classB_std = np.std(classB)
print("")
print("-------------Standard Deviation-----------------")
print('Class A standard_deviation',classA_std )
print('Class B standard_deviation',classB_std )
print("------------------------------------------------")


--------------------Mean----------------------
Class A Score Average 90.0
Class B Score Average 86.0
----------------------------------------------

----------------Variance-----------------------
Class A variance 11.6
Class B variance 114.0
------------------------------------------------

-------------Standard Deviation-----------------
Class A standard_deviation 3.40587727318528
Class B standard_deviation 10.677078252031311
------------------------------------------------


In [25]:
scores = np.array([80,89,78,50,66,95,45,49,70])
np.save('student_score.npy',scores)
load_file = np.load('student_score.npy')
print("Original Score:",scores)
print("Loaded Score:",load_file)

Original Score: [80 89 78 50 66 95 45 49 70]
Loaded Score: [80 89 78 50 66 95 45 49 70]
